language: java
script:
  - ant all
# blocklist
branches:
  except:
  - development 

# safelist
branches:
  only:
  - stable
  - master
deploy:
  provider: heroku 
  api_key: HEROKU API KEY HERE 
  app: taco-shack
