language: java
# blocklist
branches:
  except:
  - development 
  - master

# safelist
branches:
  only:
  - build 
deploy:
  provider: heroku 
  api_key: d33fdbe5-5fe6-48bd-9821-d5cd9ae4ba32 
  app: taco-shack
